Added handlebar helpers for cowin APIs
projectstepone/statesman pull request #29
Opened 2021-07-06 21:55 UTC by sandeepanbaidya

1) Handlebar helpers like sha256 for OTP and increment date functions
2) Added acceptable error codes in HTTPActionTemplate

2021-07-07 02:26 UTC, santanusinha requested changes

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/action/impl/HttpAction.java
> +                if ((actionData.acceptableErrorCode == null
Use accessors

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/action/impl/HttpAction.java
> +                if ((actionData.acceptableErrorCode == null
This condition looks weird.. what you are trying to do is:
`if((actionData.acceptableErrorCode != null && !actionData.acceptableErrorCode.contains(response.code()))
    || !response.isSuccessful())`

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/action/impl/HttpAction.java
> +                if ((actionData.acceptableErrorCode == null
Fix the condition like above. Maybe extract a method

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/action/impl/HttpAction.java
> +        private List<Integer> acceptableErrorCode;
Set not list

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
Move to private static final

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                    return sdf.format(c.getTime());
`Date.from(Instant.now().....)` instead of this?

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    private void registerIncDate() {
Add testcases for this

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/pom.xml
> +        <dependency>
This is not needed for sha256. See below

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +        handlebars.registerHelper("sha256",(Integer context, Options options) -> {
Why not take Object here and use return of context.toString() to generate sha256?

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +            return "0";
Why return zero here? Return null.

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                e.printStackTrace();
Remove this

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                return "0";
There is no need for this.

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                    return new String(hex.encode(hash));
This is not needed. All required stuff is present in Java core libs already.
```
MessageDigest digest = MessageDigest.getInstance("SHA-256");
byte[] hash = digest.digest(context.toString().getBytes(StandardCharsets.UTF_8));
```

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    private static final String OUT_FILE = "~/flipkart/statesman/certificate.pdf";
What is this? Remove this

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    private final Hex hex;
Not needed. Remove this

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    public static HandleBarsHelperRegistry newInstance(Handlebars handlebars, Clock clock, Hex hex) {
Remove

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    private HandleBarsHelperRegistry(Handlebars handlebars, Clock clock, Hex hex) {
Remove the extra param

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +    private void registerSHA256() {
Add testcases

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsService.java
> +        this(Clock.system(ZoneId.of(DateUtils.getLocalZone())), new Hex());
Revert all changes

2021-07-07 02:26 UTC, santanusinha commented on statesman-engine/src/test/java/io/appform/statesman/engine/handlebars/HandleBarsServiceTest.java
> +        val hb = new HandleBarsService(fixedTime, null);
Revert all changes. Add testcases for new functions

2021-07-07 02:26 UTC, santanusinha commented on statesman-model/src/main/java/io/appform/statesman/model/action/template/HttpActionTemplate.java
> +    private List<Integer> acceptableErrorCodes;
Set

2021-07-08 05:51 UTC, santanusinha requested changes

2021-07-08 05:51 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/action/impl/HttpAction.java
> +    private boolean isNotSuccessful(Response response, HttpActionData actionData) {
Do not write negative test. Negate in if clause if needed.

2021-07-08 05:51 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                    c.add(Calendar.DATE, context);
Use instant api to increment.
```
       return  SIMPLE_DATE_FORMAT.format(Date.from(Instant.now().plus(context, ChronoUnit.DAYS)).getTime());
```

2021-07-08 05:51 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsHelperRegistry.java
> +                if (null != context) {
If context is null, set it to 1, so {{incDate}} will automatically give you next day

2021-07-08 05:51 UTC, santanusinha commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsService.java
> +import org.apache.commons.codec.binary.Hex;
Remove unused import

2021-07-08 05:51 UTC, santanusinha commented on statesman-engine/src/test/java/io/appform/statesman/engine/handlebars/HandleBarsServiceTest.java
> +        c.add(Calendar.DATE, 1);
Do not use calendar api, use the new Instant api

2021-07-08 05:51 UTC, santanusinha commented on statesman-model/src/main/java/io/appform/statesman/model/action/template/HttpActionTemplate.java
> +    private Set<Integer> acceptableErrorCodes;
Rename as discussed

2021-07-08 07:35 UTC, sandeepanbaidya commented on statesman-engine/src/main/java/io/appform/statesman/engine/handlebars/HandleBarsService.java
> +import org.apache.commons.codec.binary.Hex;
This is being used for sha256

2021-07-08 11:26 UTC, santanusinha approved these changes

2021-07-08 11:27 UTC, merged